# Generated by Django 5.2.8 on 2026-01-07 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("docstoremanagerbackend", "0001_init"),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "storage",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(default="password", max_length=128)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")],
                        default="user",
                        max_length=50,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelves",
                        to="docstoremanagerbackend.storage",
                    ),
                ),
            ],
            options={
                "db_table": "shelf",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("report", "Report"),
                            ("invoice", "Invoice"),
                            ("contract", "Contract"),
                            ("memo", "Memo"),
                        ],
                        default="report",
                        max_length=100,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="docstoremanagerbackend.shelf",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="docstoremanagerbackend.storage",
                    ),
                ),
            ],
            options={
                "db_table": "document",
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("viewed", "Viewed"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("storage", "Storage"),
                            ("shelf", "Shelf"),
                            ("document", "Document"),
                        ],
                        max_length=255,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="docstoremanagerbackend.user",
                    ),
                ),
            ],
            options={
                "db_table": "log_entry",
            },
        ),
    ]
